name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X GET "http://192.168.33.10/job/SPRINGAOC/build?token=1112884d89f697c516e888f003b7d5e95d" 
